### ISSUE TITLE
run every minute ?

### ISSUE THREAD

**Issue by Helias** [QD-2022/Healthcheck-bot#37]
if we run this every minute and a service is down, we will receive every minute via telegram that the service is down and it will be a bit annoying

we should find a way to make the healthcheck every minute but if a service has been already "alerted" we should not send any alert for at least 1 hour (or 24 hours?)

note: current workaround -> we'll run the healthcheck bot every 30 minutes to receive only 48 messages per day in the worst case 😅

**Comment by domenicoblanco** [comment]
A simple approach would be to store a dict with the faulty url and a timestamp, and send another notification after 12h/24h

**Comment by Helias** [comment]
In past, we detected some scenarios where the service was available but the answer from an HTTP request failed, then we received all night random notifications about it
we should be sure that the service is down, we could set a retry-param of 10 to be 100% sure that the service is down

**Comment by Helias** [comment]
we run it every day from now
