### ISSUE TITLE
pyrogram healthcheck bot

### ISSUE THREAD

**Issue by Helias** [QD-2022/Healthcheck-bot#41]
we should implement a pyrogram bot that speaks with our current bot and make a daily healthcheck

**Comment by domenicoblanco** [comment]
The only "problem" is that we need to create an application credentials and access with a real user account...

**Comment by Helias** [comment]
that's not a problem, I could use my second account for this

**Comment by domenicoblanco** [comment]
I'll try to give it a look during the weekend c:
